locality_mapping = {
    'Kilpauk': 'Locality_211',
    'Chromepet': 'Locality_53',
    'Triplicane': 'Locality_172',
    'Alwarpet': 'Locality_132',
    'Ambattur': 'Locality_422',
    'Porur': 'Locality_120',
    'Mandaveli': 'Locality_280',
    'Avadi': 'Locality_240',
    'Vepery': 'Locality_30',
    'Teynampet': 'Locality_189',
    'Velachery': 'Locality_111',
    'Nungambakkam': 'Locality_52',
    'Kodambakkam': 'Locality_57',
    'Thiruvanmiyur': 'Locality_59',
    'Egmore': 'Locality_88',
    'Perambur': 'Locality_49',
    'Koyambedu': 'Locality_314',
    'Royapettah': 'Locality_1',
    'Vyasarpadi': 'Locality_394',
    'Tambaram': 'Locality_187',
    'Saidapet': 'Locality_420',
    'T Nagar': 'Locality_181',
    'Mylapore': 'Locality_179',
    'Ashok Nagar': 'Locality_180',
    'Medavakkam': 'Locality_326',
    'Sholinganallur': 'Locality_384',
    'Vadapalani': 'Locality_430',
    'Pallavaram': 'Locality_363',
    'Adyar': 'Locality_83',
    'Guindy': 'Locality_435',
    'Choolaimedu': 'Locality_442',
    'Anna Nagar': 'Locality_397',
}
